{'application': False,
 'author': 'Nedas Zilinskas',
 'auto_install': False,
 'category': 'Sales,Website',
 'contributors': 'Nedas Zilinskas',
 'currency': 'EUR',
 'data': ['data/product_pricelist.xml',
          'views/res_partner_hcategory.xml',
          'views/res_partner.xml'],
 'demo': [],
 'depends': ['product', 'sale', 'website_sale', 'partner_category_hierarchy'],
 'external_dependencies': [],
 'images': ['static/description/main_screenshot.png'],
 'installable': True,
 'license': 'AGPL-3',
 'live_test_url': 'http://minilini.com/page/start',
 'maintainer': 'Nedas Zilinskas',
 'name': 'Pricelist by Partner Category',
 'price': 20.0,
 'qweb': [],
 'summary': 'Manage Pricelists by Partner Category',
 'support': 'nedas.zilinskas@gmail.com',
 'version': '11.0.1.0.0',
 'website': 'http://nedaszilinskas.com'}
