{'application': False,
 'author': 'Nedas Zilinskas',
 'auto_install': False,
 'category': 'Sales,Website',
 'contributors': 'Nedas Zilinskas',
 'currency': 'EUR',
 'data': ['views/res_partner_hcategory.xml',
          'views/product_public_category.xml',
          'views/res_partner.xml'],
 'demo': [],
 'depends': ['website_sale', 'partner_category_hierarchy'],
 'external_dependencies': [],
 'images': ['static/description/main_screenshot.png'],
 'installable': True,
 'license': 'AGPL-3',
 'live_test_url': 'http://minilini.com/page/start',
 'maintainer': 'Nedas Zilinskas',
 'name': 'Product Category Visibility',
 'price': 40.0,
 'qweb': [],
 'summary': 'Manage product category visibility by partner category',
 'support': 'nedas.zilinskas@gmail.com',
 'version': '11.0.1.0.0',
 'website': 'http://nedaszilinskas.com'}
