{'application': False,
 'author': 'Nedas Zilinskas',
 'auto_install': False,
 'category': 'Extra Tools,Productivity',
 'contributors': 'Nedas Zilinskas',
 'currency': 'EUR',
 'data': ['security/ir.model.access.csv',
          'views/res_partner.xml',
          'views/res_partner_hcategory.xml'],
 'demo': [],
 'depends': ['base'],
 'external_dependencies': [],
 'images': ['static/description/main_screenshot.png'],
 'installable': True,
 'license': 'AGPL-3',
 'live_test_url': 'http://minilini.com/page/start',
 'maintainer': 'Nedas Zilinskas',
 'name': 'Partners Hierarchy',
 'price': 10.0,
 'qweb': [],
 'summary': 'Build parters hierarchy by specifying partner categories',
 'support': 'nedas.zilinskas@gmail.com',
 'version': '11.0.1.0.0',
 'website': 'http://nedaszilinskas.com'}
